### PR TITLE
web build

### PR DESCRIPTION
**Pull request by benauthor**
@jdiedrick i noticed the gh-pages branch appears hand-generated, i hope this is useful.

if you want to regenerate `text.html`, just

    cd web
    make install_markdown
    make build

### CODE REVIEW

**Comment by benauthor** [comment]
seems like you figured this out a different way 😎 , should i close?

**Comment by johanndiedrick** [comment]
@benauthor i want to merge this somehow! i missed this pr and diverged a bit. i haven't had a chance to sit down and look at it. i think its still useful though! let me take a look at it and see if its still merge-able.

**Comment by benauthor** [comment]
@jdiedrick no big deal, it was just a quick script to save manual labor getting from existing markdown to something like where you are now in your gh-pages branch. but now you're there! 🦄

**Comment by johanndiedrick** [comment]
@benauthor merged! thanks for this :)

**Pull request merged**
